// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeEawxwlZEYwYrUUvMcurd9Jv4LyYsSrA',
    appId: '1:405658918947:web:43c74aad82645743a2d196',
    messagingSenderId: '405658918947',
    projectId: 'startupignition-93cac',
    authDomain: 'startupignition-93cac.firebaseapp.com',
    storageBucket: 'startupignition-93cac.appspot.com',
    measurementId: 'G-BER9K9J2MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJqxzEu2jSZE1BoPws1Pvr_JoQ-T80t8',
    appId: '1:405658918947:android:ab97392599a532cfa2d196',
    messagingSenderId: '405658918947',
    projectId: 'startupignition-93cac',
    storageBucket: 'startupignition-93cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNe2D56GkkfpIvu7ZduP0E_qF9Y_sINVk',
    appId: '1:405658918947:ios:1970b7aa651b8027a2d196',
    messagingSenderId: '405658918947',
    projectId: 'startupignition-93cac',
    storageBucket: 'startupignition-93cac.appspot.com',
    androidClientId:
        '405658918947-s8819hcdkh7mmu57407pieseg5d5pjah.apps.googleusercontent.com',
    iosBundleId: 'com.example.sitproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNe2D56GkkfpIvu7ZduP0E_qF9Y_sINVk',
    appId: '1:405658918947:ios:2e98f63f14e8414fa2d196',
    messagingSenderId: '405658918947',
    projectId: 'startupignition-93cac',
    storageBucket: 'startupignition-93cac.appspot.com',
    androidClientId:
        '405658918947-s8819hcdkh7mmu57407pieseg5d5pjah.apps.googleusercontent.com',
    iosBundleId: 'com.example.sitproject.RunnerTests',
  );
}
